var sentinel = ee.ImageCollection("COPERNICUS/S2_HARMONIZED")
Map.centerObject(ROI, 12)
var clipped = sentinel.filterBounds(ROI)
print(clipped.size())
var filterdata = ((clipped.filter(ee.Filter.lt('CLOUDY_PIXEL_PERCENTAGE', 1))).filterDate('2017-1-1' , '2026-7-28')).median().clip(ROI)
print (filterdata)
Map.addLayer(filterdata)
Map.addLayer(filterdata, imageVisParam7 , 'False')
Map.addLayer(filterdata, imageVisParam6 , 'True')
Map.addLayer(filterdata, imageVisParam5 , 'agriculture')